apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-python
  namespace: nautible-app-examples
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-examples-python
        image: nautibledevacr.azurecr.io/nautible-app-examples-python:latest
        imagePullPolicy: Never
        env:
        - name: LOG_LEVEL # CRITICAL, ERROR, WARNING, INFO, DEBUG
          value: DEBUG
        - name: LOG_FORMAT # json, console
          value: console
