apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-node
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-node
        image: nautibledevacr.azurecr.io/nautible-app-examples-node:4da9bf154458cd83eb0e91b0936731204fd026d3
        env:
        - name: LOG_LEVEL # error, warn, info, verbose, debug
          value: info
