kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: public.ecr.aws/nautible/nautible-app-examples-java:33646893714958ef012e81ebb1eeff2a493a7a55
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
