kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: public.ecr.aws/nautible/nautible-app-examples-java:b50f4137710b601d41282fc40e64e39990b8da4a
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
