kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: public.ecr.aws/nautible/nautible-app-examples-java:33103131e7618396c031497aaa3a78a02f945687
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
