kind: Deployment
apiVersion: apps/v1
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: public.ecr.aws/nautible/nautible-app-examples-java:52bc1fdedd223b01cd77ed0af7d3f350378fca7d
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
