apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
        - name: nautible-app-examples-java
          image: public.ecr.aws/nautible/nautible-app-examples-java:688cca610abf2b8372afc18e77dfef9ad3ac8255
          env:
            - name: QUARKUS_PROFILE
              value: aws-dev
