apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-python
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-python
        image: public.ecr.aws/nautible/nautible-app-examples-python:560bc7f9a1a26cca56f45fcb93d1d2f14641155f
        env:
        - name: LOG_LEVEL # CRITICAL, ERROR, WARNING, INFO, DEBUG
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
