apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-node
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-node
        image: public.ecr.aws/nautible/nautible-app-examples-node:8c8ebb30be2909a9676f3c8474af111704ddd90c
        env:
        - name: LOG_LEVEL # error, warn, info, verbose, debug
          value: info
