apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-node
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-node
        image: public.ecr.aws/nautible/nautible-app-examples-node:560bc7f9a1a26cca56f45fcb93d1d2f14641155f
        env:
        - name: LOG_LEVEL # error, warn, info, verbose, debug
          value: info
