apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        imagePullPolicy: Never
        env:
        - name: QUARKUS_PROFILE
          value: aws-local-dev
