apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-go
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-go
        image: public.ecr.aws/nautible/nautible-app-examples-go:ee6cce6463b1b34971a334e74306931830bbc170
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
