apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-go
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-go
        image: public.ecr.aws/nautible/nautible-app-examples-go:25a07a4088d8c2e481c50c69e086e8919e16048e
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
