apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-go
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-go
        image: public.ecr.aws/nautible/nautible-app-examples-go:5678aaea9ae2e6dbbd42a4e88e8fa19ed587a81a
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
