apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-go
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-go
        image: public.ecr.aws/nautible/nautible-app-examples-go:80d67709523d89322880240879e1fc2a6e8174e4
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
