apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: nautibledevacr.azurecr.io/nautible-app-examples-java:ee6cce6463b1b34971a334e74306931830bbc170
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
