apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: nautibledevacr.azurecr.io/nautible-app-examples-java:4da9bf154458cd83eb0e91b0936731204fd026d3
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
