apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-node
  namespace: nautible-app-examples
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-examples-node
        image: nautibledevacr.azurecr.io/nautible-app-examples-node:latest
        imagePullPolicy: Never
        env:
        - name: LOG_LEVEL # error, warn, info, verbose, debug
          value: debug
