apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-examples-java
  namespace: nautible-app-examples
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-examples-java
        image: nautibledevacr.azurecr.io/nautible-app-examples-java:latest
        imagePullPolicy: Never
        env:
        - name: QUARKUS_PROFILE
          value: azure-local-dev
